### ISSUE TITLE
It totally breaks game

### ISSUE THREAD

**Issue by PryzhokNaRobote** [Weebifying/high-graphics-android-geode#1]
![Screenshot_2024-02-21-15-49-55-72_73932565f5d18c5d7f2b58eb6d5de17f](https://github.com/Weebifying/high-graphics-android-geode/assets/156057628/c9487f8e-f00b-4fa0-859a-d2d540661205)
How?

**Comment by Weebifying** [comment]
it is very important to read
![image](https://github.com/Weebifying/high-graphics-android-geode/assets/70783792/ccd32296-675c-499f-a049-fe811b4ac62d)

**Comment by Weebifying** [comment]
well i guess i will add the disclaimer in readme as well

**Comment by PryzhokNaRobote** [comment]
So, I just loaded textures from PC and it works successful!

ср, 21 февр. 2024 г., 18:14 Weebifying ***@***.***>:
