### ISSUE TITLE
Lines in objects

### ISSUE THREAD

**Issue by Cosmic3009** [Weebifying/high-graphics-android-geode#12]
There is some lines like in almost every object 
![Screenshot_2024-03-08-12-05-29-337_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/162670039/2e8b5ba0-6e93-42ba-8cd4-39bab39b23c8)

![Screenshot_2024-03-08-13-30-20-033_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/162670039/d66fb6d4-4aed-4496-8c87-f33993f07342)

**Comment by Weebifying** [comment]
its a per-device bug, i cant do anything about it
