### ISSUE TITLE
The textures do not work as desired.

### ISSUE THREAD

**Issue by ghost** [Weebifying/high-graphics-android-geode#15]
![Screenshot_2024-03-27-08-34-03-920_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/14f47309-b0e1-4454-8126-acfedb4b03ab)
![Screenshot_2024-03-27-08-33-46-201_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/d2f78e72-dc39-46fc-8d2c-5c2b504e88b4)
![Screenshot_2024-03-27-08-33-40-276_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/7d97c0fe-6fd8-4ab9-900c-20047e61f53e)
![Screenshot_2024-03-27-08-33-13-072_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/8186d902-20d2-4f4e-a2ab-98e95e1eec60)
![Screenshot_2024-03-27-08-33-16-908_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/89476f7d-777c-49e0-8e1c-4a56c206cafc)
![Screenshot_2024-03-27-08-33-05-673_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/50a6396c-b482-4262-9114-23145b40babf)
![Screenshot_2024-03-27-08-31-33-536_com mi android globalFileexplorer](https://github.com/Weebifying/high-graphics-android-geode/assets/165131942/04dd9087-e85a-466e-aab2-24f096927438)

**Comment by RainalGd** [comment]
My phone is Xiaomi Redmi 10C

**Comment by RainalGd** [comment]
My phone is Xiaomi Redmi 10C

**Comment by Weebifying** [comment]
ermm you are supposed to put the `high-textures` folder in Texture Loader's `packs` folder
