### ISSUE TITLE
Futura UI

### ISSUE THREAD

**Issue by Denyscrasav4ik** [Weebifying/high-graphics-android-geode#2]
When i uplied futura ui high texture pack with this mod the ground is underground (literally i cant explain it)
![Screenshot_2024-02-24-08-58-50-749_com geode launcher-edit](https://github.com/Weebifying/high-graphics-android-geode/assets/147797215/60352a8d-c34a-4620-8780-48a6ad5a0ee2)

(the black is where the ground is supposed to be but the ground is under it)

Also in main menu its the same thing

**Comment by Weebifying** [comment]
??

**Comment by Denyscrasav4ik** [comment]
https://github.com/Weebifying/high-graphics-android-geode/assets/147797215/75db273a-fe0c-4094-9296-b015674868e8

**Comment by Weebifying** [comment]
I can't replicate your bug. Did you unzip the high-textures zip file and then load the resulting folder instead of loading the zip file directly using Texture Loader?

**Comment by Denyscrasav4ik** [comment]
I loaded the folder and im starting to think its display size issues

**Comment by Weebifying** [comment]
I have the same resolution and no issue to be found...

**Comment by Denyscrasav4ik** [comment]
then its FUTURA UI texture pack issue or smth because i checked the mod incompability and i didnt found it

**Comment by Weebifying** [comment]
Can you try taking off futura ui and see if the issue still persists?

**Comment by Weebifying** [comment]
Can you try taking off futura ui and see if the issue still persists?

**Comment by Denyscrasav4ik** [comment]
i guess futura ui is broken because i uplied normal high textures and everything works fine
