### ISSUE TITLE
Textures are not maintained 

### ISSUE THREAD

**Issue by GaryAlex506** [Weebifying/high-graphics-android-geode#20]
I have a problem which is that when I load the high textures they work fine But once I close the game and reopen it the textures automatically go down to Medium Quality, Any solution?

**Comment by Weebifying** [comment]
can you try completing a level, quit the game, relaunch it and see if the completion is saved

**Comment by GaryAlex506** [comment]
> ¿Puedes intentar completar un nivel, salir del juego, reiniciarlo y ver si se guarda la finalización?

**Comment by GaryAlex506** [comment]
I've tried everything and it's still the same, I don't know what to do...

**Comment by FaduroAlmazo** [comment]
The same is happening, whenever I'm in high quality and play and do stuff, and then a close the game y re enter, I'm back to medium quality and all the progress a did disappeared.
