### ISSUE TITLE
NCS Logos, gauntlets and other textures are missing 

### ISSUE THREAD

**Issue by TheWerelionwolf** [Weebifying/high-graphics-android-geode#21]
Basically update 2.206 had a texture update with new icons (logos) and buttons such as NCS logos next to song names, the NCS button in the music selector in the editor also level complete screen where the texture is missing for the respawn from the last checkpoint and the hide end level stats overlay icon (the eye with a diagonal line crossed off)

![Screenshot_20240622_225604_Geode](https://github.com/Weebifying/high-graphics-android-geode/assets/147426725/3591b793-137c-4782-8a1e-a3385d855e56)
![Screenshot_20240622_225629_Geode](https://github.com/Weebifying/high-graphics-android-geode/assets/147426725/c6f1428a-c15b-44da-9d16-9c7bb4d430fd)
![Screenshot_20240622_225738_Geode](https://github.com/Weebifying/high-graphics-android-geode/assets/147426725/a7e33908-b299-4392-a355-6be9bf957987)

**Comment by Weebifying** [comment]
lmao, I'm pretty sure you just haven't downloaded the updated 2.206 textures provided by the mod

**Comment by TheWerelionwolf** [comment]
> lmao, I'm pretty sure you just haven't downloaded the updated 2.206 textures provided by the mod

I'm pretty sure you didn't update the google drive file or have a new link to the new high textures pack, when I click "here" on the mod menu it sends me to here
![Screenshot_20240623_095654_Chrome](https://github.com/Weebifying/high-graphics-android-geode/assets/147426725/99fbfa8e-f063-4e5b-ac9b-37149a7c7840)

**Comment by TheWerelionwolf** [comment]
I got the high textures but outside of the mod client, had to go on geode's main website for it

**Comment by Weebifying** [comment]
> > lmao, I'm pretty sure you just haven't downloaded the updated 2.206 textures provided by the mod
> 
> I'm pretty sure you didn't update the google drive file or have a new link to the new high textures pack, when I click "here" on the mod menu it sends me to here ![Screenshot_20240623_095654_Chrome](https://private-user-images.githubusercontent.com/147426725/342069793-99fbfa8e-f063-4e5b-ac9b-37149a7c7840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTczOTksIm5iZiI6MTcxOTE1NzA5OSwicGF0aCI6Ii8xNDc0MjY3MjUvMzQyMDY5NzkzLTk5ZmJmYThlLWYwNjMtNGU1Yi1hYzliLTM3MTQ5YTdjNzg0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNTM4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWIwMzc5OWI4NzAxYjMxMTZjZjgxYTk4YzA3ZGRmZjBkNmEzOTY3NWY4MWE4MWZjNGU1MDc2ZDE2NzYwOWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._Jz2jfAwKm0bhL6n04aCOadKyUTZC6KPo3LZ5RmkDqM)

oh thats my bad haha i forgot to change the link heres the new one https://drive.google.com/drive/folders/1kLSaVvQuGQvvI_hT0p6doAHAtTrVy_uM?usp=sharing
