### ISSUE TITLE
Progress loss

### ISSUE THREAD

**Issue by FaduroAlmazo** [Weebifying/high-graphics-android-geode#22]
Whenever I'm in high quality and play and do stuff, and then i close the game and re enter, I'm back to medium quality and all the progress a did disappeared. Is there a solution?
And i already check that is always in high quality, and with this mod.

**Comment by Vendeta387** [comment]
Try disabling the pop up setting in the mod setting  that worked for me

**Comment by Weebifying** [comment]
> Try disabling the pop up setting in the mod setting that worked for me

what... how did it even work lmao

also, can you try uninstalling and reinstalling the geode app, it worked for some people
