### ISSUE TITLE
What

### ISSUE THREAD

**Issue by BlazONBZ** [Weebifying/high-graphics-android-geode#23]
I downloaded new updated 2.206 textures, but they are still missing for unknown reason. What is stranger, in texture file itself 2.206 textures are present, but in game they aren't.

![IMG_20240630_005953](https://github.com/Weebifying/high-graphics-android-geode/assets/174212007/41b91ee1-41b8-40ca-a263-f935e00d1eb6)

![Screenshot_2024-06-30-00-56-59-118_com geode launcher](https://github.com/Weebifying/high-graphics-android-geode/assets/174212007/f563263e-912e-4838-95ad-97901f7a4c0b)

![IMG_20240630_005911](https://github.com/Weebifying/high-graphics-android-geode/assets/174212007/08433fb0-cabf-4312-866f-bf03bb043b64)

**Comment by Weebifying** [comment]
You need to add the pack to Texture Loader's `packs` folder, which should be located at  `.../com.geode.launcher/game/geode/config/geode.texture-loader/packs/`, THEN **load the pack**

**Comment by BlazONBZ** [comment]
> You need to add the pack to Texture Loader's `packs` folder, which should be located at `.../com.geode.launcher/game/geode/config/geode.texture-loader/packs/`, THEN **load the pack**

Ooooh, turns out the textures were just in the wrong place. Now 2.206 textures are present. Thank you.
