### ISSUE TITLE
Texture pack

### ISSUE THREAD

**Issue by Vendeta387** [Weebifying/high-graphics-android-geode#25]
The 2.206 high texture pack isnt showing up even though it sais that 5 packs got loaded
![Screenshot_20240721_113616_Geode](https://github.com/user-attachments/assets/2599b7fc-b012-4b89-81bc-fb4c4cd0c3ac)

**Comment by Weebifying** [comment]
you have to remove the old 2.204 pack...

**Comment by Weebifying** [comment]
looks like it's missing the ncs logo... are you sure you are using the 2.206 version

**Comment by Vendeta387** [comment]
Yeah, I downloaded it trough the mod pop up.

**Comment by Weebifying** [comment]
is the name of the pack "High Graphics (2.206)"

**Comment by Vendeta387** [comment]
For me it's high-textures-2.206

**Comment by Vendeta387** [comment]
Is it maybe the wrong file you put in the drive link? The new file has only 3 or 4 more things in the folder is maybe something wrong with that

**Comment by Vendeta387** [comment]
Never mind I just solved the problem. It wasn't the high texture pack all along it was the other texture pack that I'm using. Sorry for making unnecessary problems lol
