### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by jaquaviousquan1** [Weebifying/high-graphics-android-geode#33]
![Screenshot_20240818_221024_Geode](https://github.com/user-attachments/assets/0f4f0f67-1ca1-467f-8586-1dccb1036973)
It makes everything tiny

**Comment by jaquaviousquan1** [comment]
![Screenshot_20240818_222433_Geode](https://github.com/user-attachments/assets/e31ee9fc-ba6c-4022-b78b-78b91779ae7e)
It also does this

**Comment by Weebifying** [comment]
are you sure you extracted the high textures folder correctly
