### ISSUE TITLE
i think i did something wrong

### ISSUE THREAD

**Issue by thetruecheeseburger** [Weebifying/high-graphics-android-geode#36]
the warning pop up appears even if the texture pack is enabled
![Screenshot_20240918_211323_com geode launcher](https://github.com/user-attachments/assets/82b0cb00-1b9b-44a6-a76f-fecd591bbfc7)
![Screenshot_20240918_211255_com geode launcher](https://github.com/user-attachments/assets/2d47be21-c7aa-4a59-933b-be4ecc064767)

**Comment by thetruecheeseburger** [comment]
i fixed it, now the problem is that now when using a high texture pack (like crafting texture pack) it crashes without giving a crash log or even the message that says (geode has crashed) it just crashes.

**Comment by Weebifying** [comment]
can you send that pack here so i can test it?

**Comment by thetruecheeseburger** [comment]
> can you send that pack here so i can test it?

[Crafting Texture Pack FINAL VERSION.zip](https://github.com/user-attachments/files/17064122/Crafting.Texture.Pack.FINAL.VERSION.zip)
