### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by nbieberitz** [Weebifying/high-graphics-android-geode#40]
Idk if this is user error, but everything's off...

![VideoCapture_20241019-002021](https://github.com/user-attachments/assets/2b91fcab-b5ff-4a5c-b982-1a239c2ba302)
![VideoCapture_20241019-002016](https://github.com/user-attachments/assets/c63fcbd2-3867-4d1b-a064-46572b76ffc5)
![VideoCapture_20241019-002013](https://github.com/user-attachments/assets/9cb81372-8220-4e15-bfd4-d8ed3aeb28f1)
![VideoCapture_20241019-002009](https://github.com/user-attachments/assets/5d98d754-453e-4e12-96d6-8c56e7097ded)
![VideoCapture_20241019-002007](https://github.com/user-attachments/assets/ee4267a4-db72-4064-9431-dedbe5e09742)
![VideoCapture_20241019-002003](https://github.com/user-attachments/assets/64f6ad55-2897-4633-af6b-0da09d20cdc2)
![VideoCapture_20241019-001953](https://github.com/user-attachments/assets/5d28e1b4-a502-4b29-a7ea-aee9e581a45b)
![VideoCapture_20241019-001947](https://github.com/user-attachments/assets/12fd757c-949c-409c-9302-f5ac139a9bec)

**Comment by Weebifying** [comment]
did you unzip the high textures pack before applying?

**Comment by sw97awesome** [comment]
> did you unzip the high textures pack before applying?

I can't even download the file on google drive for some reason

**Comment by nbieberitz** [comment]
How though?

**Comment by Weebifying** [comment]
Can you answer my question

**Comment by nbieberitz** [comment]
No, I didn't, because I didn't know how.
