### ISSUE TITLE
where did i go wrong

### ISSUE THREAD

**Issue by builtdiff7** [Weebifying/high-graphics-android-geode#41]
Android>Media>com.geode.launcher>game>geode>config>geode.texture.loader>packs     and i put the unzipped pack in there yet nothing happened

![Screenshot_2024-10-24-23-42-58-025_ru zdevs zarchiver](https://github.com/user-attachments/assets/23a807b1-aa64-4c3c-bdd8-3d935a370842)

![Screenshot_20241024-234237](https://github.com/user-attachments/assets/ed918945-9b27-41b8-bdcc-fbb2a6b73aac)

![Screenshot_2024-10-24-23-42-50-501_ru zdevs zarchiver](https://github.com/user-attachments/assets/d6b538fa-552d-4a92-995f-0efc9245fd8b)

**Comment by Weebifying** [comment]
the textures need to be contained in another folder inside the `packs` folder... so like ...geode.texture-loader > packs > high-textures > [ALL FILES HERE]

**Comment by builtdiff7** [comment]
i have to make a folder? because when i downloaded it, its not in a folder

**Comment by builtdiff7** [comment]
ok, i tried it and it worked. thanks dude, great mod
