### ISSUE TITLE
I cant download the file from google drive

### ISSUE THREAD

**Issue by sw97awesome** [Weebifying/high-graphics-android-geode#42]
![Screenshot_20241025_070025_Drive](https://github.com/user-attachments/assets/6c9ebcf6-88db-4fe1-8be0-5b9f8143d20c)

**Comment by Weebifying** [comment]
can you try opening the link in your browser instead of the app?

**Comment by sw97awesome** [comment]
> can you try opening the link in your browser instead of the app?

I'm able to download the file, but when I load the texture pacn using texture loader it looks weird. Did I do something wrong?
![Screenshot_20241026_104018_Geode](https://github.com/user-attachments/assets/74aebe88-76e3-4c05-9d31-d7dea5685f58)

**Comment by Weebifying** [comment]
> I'm able to download the file, but when I load the texture pack using texture loader it looks weird. Did I do something wrong?

did you extract the pack folder?

**Comment by sw97awesome** [comment]
> > I'm able to download the file, but when I load the texture pack using texture loader it looks weird. Did I do something wrong?
> 
> did you extract the pack folder?

yes

**Comment by TheKazio14** [comment]
Download Link for High Graphics on Android for GD 2.207:https://www.mediafire.com/file/k0oojb3848t7jhm/high-textures-2.207.zip/file
