### ISSUE TITLE
The texture pack is not loading

### ISSUE THREAD

**Issue by G4vro1D** [Weebifying/high-graphics-android-geode#45]
When a pop-up window appears and I click the "Download" button, it writes the following: Error extracting: Cannot find folder. When I go to the folder where this texture pack should be located, I find only an empty file there "2.2074.zip". When I checked the source code of the mod, I found a link to catbox.moe, and later found out that this site does not work (at least for me). What should I do about it? Is it possible to get an alternative link to download the file?

**Comment by Weebifying** [comment]
use a vpn

**Comment by Weebifying** [comment]
> I found a link to catbox.moe, and later found out that this site does not work (at least for me).

also, which country are you from?

**Comment by G4vro1D** [comment]
I've already used a vpn and it didn't help. I'm from Russia.

**Comment by Weebifying** [comment]
> I've already used a vpn and it didn't help. I'm from Russia.

Can you update the mod and try again? I just made an update that added a backup download in case the primary one (catbox.moe) fails.

**Comment by G4vro1D** [comment]
Oh yes, it works now. Thank you very much!
