### ISSUE TITLE
Graphical problems

### ISSUE THREAD

**Issue by Rhythm-RiderGD** [Weebifying/high-graphics-android-geode#47]
Hi, so I figured out that some textures are missing or corrupt. The icons for the game mode switchers aren't there and some glow objects and other bits are corrupted, I'll send the image below.

![Screenshot_20241125_161542_Geode](https://github.com/user-attachments/assets/f64139c4-f6d5-4120-b4e2-ebc1c1ad3026)

Geode: version 4.0.1

Android Version: Android 14 (OneUI 6.1)

Everything is up to date. I just feel like there are a few bugs in the latest update for the mod. If (by any chance) could you maybe update the files for 2.2074 HG files?

**Comment by Rhythm-RiderGD** [comment]
The level I used was "The Final Realm" my Masterthecube5

**Comment by Weebifying** [comment]
It works completely fine for me, which most likely means that it's a device-specific problem, which I can't help with.

**Comment by Rhythm-RiderGD** [comment]
Ah, okay. I hoped that wasn't the case. Because with the 2.206 version nothing happened with the textures and they were grand. I run on a SM-A346B (Samsung A34 5G 256GB, 8GB)

**Comment by Rhythm-RiderGD** [comment]
So I have looked through the game sheets and I did find that the icons and textures ARE there, but not being found in GD. I wonder why that is...

**Comment by Rhythm-RiderGD** [comment]
I found another texture glitch that happens to the robot game mode and some collectibles (a coin) 

![Screenshot_20241126_081250_Geode](https://github.com/user-attachments/assets/cfb0df89-e9f3-436e-88e1-63e00dea6ca6)

Do you want/ need any log files to see? Because I feel like it is just that the game isn't finding the icon coordinates correctly on the spreadsheet.

**Comment by Weebifying** [comment]
Oh, that just looks completely broken lol. Can you try deleting the `2.2074` folder inside this mod's config folder? (`Android/media/com.geode.launcher/game/geode/config/weebify.high-graphics.android`) and try again?

**Comment by Rhythm-RiderGD** [comment]
I did do that already and redownload and it did not fix the problem. Is there any way to force the mod to use the backup link to the download because maybe the other one got corrupted somehow during upload?

I honestly have zero clue what could be the problem. I just know everything is up to date and I'm not using any texture packs that may be older.

**Comment by Rhythm-RiderGD** [comment]
I have figured out the problem. It was one of the texture packs I was using. It's called "Blank Icons V2" and it seemingly messed with some of the textures. But no other one has been the culprit. So problem is solved! 😁
