### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BlobOfficial** [Weebifying/high-graphics-android-geode#48]
Whenever I go to the settings to load high graphics, the game crashes! And when I load back in, it sets back to auto.

**Comment by Weebifying** [comment]
Can you send the crashlog, as well as the state of this mod's config folder if possible?

**Comment by BlobOfficial** [comment]
The thing is when the game "crashes" it doesn't ask me to see the crashlog like it normally would, and when I went into the crashlog, it didn't show any crashes from after Nov 7.

**Comment by BlobOfficial** [comment]
> Can you send the crashlog, as well as the state of this mod's config folder if possible?

The crashlog didn't update when it crashed, but I can send the config folder

**Comment by BlobOfficial** [comment]
Nvm I think it just had a problem with loading medium textures on globed while being in high mode

**Comment by Weebifying** [comment]
> Nvm I think it just had a problem with loading medium textures on globed while being in high mode

what

**Comment by BlobOfficial** [comment]
I think that the game was loading the medium textures on globed while it was on high graphics mode so it started being confused and crashed

**Comment by BlobOfficial** [comment]
So I just disabled globed switched to high graphics then turned it back on

**Comment by BlobOfficial** [comment]
All good!🙂
