### ISSUE TITLE
Icons Are weird

### ISSUE THREAD

**Issue by Osieeq** [Weebifying/high-graphics-android-geode#5]
So I've just started using this and the icons are not right. They are appearing smaller than usual, the robot's look much longer and the spider is just disassembled ![Screenshot_20240226-214749](https://github.com/Weebifying/high-graphics-android-geode/assets/128102988/bf75dcfa-133b-4d69-a34f-a081a3fb7435)

**Comment by Weebifying** [comment]
did you unzip your high-textures zip file

**Comment by KipivasGD** [comment]
This happened to me to
