### ISSUE TITLE
Can UHD texture pack work with this mod on mobile?

### ISSUE THREAD

**Issue by UnimosityIrux** [Weebifying/high-graphics-android-geode#6]
I downloaded one UHD texture pack, and it doesn't seem like working. Can you do anything with it? Thank you :)

**Comment by Weebifying** [comment]
have you loaded it using texture loader

**Comment by UnimosityIrux** [comment]
Yes

**Comment by UnimosityIrux** [comment]
Oh, do I need to change the textures of the mod?

**Comment by Weebifying** [comment]
the high-textures pack should be put at the very bottom of the loaded packs

**Comment by UnimosityIrux** [comment]
Oh, if I got it right, geometry dash just don't see the changed uhd texture because it wasn't in the vanilla files

**Comment by UnimosityIrux** [comment]
I don't have any explanation of why it doesn't work...

**Comment by UnimosityIrux** [comment]
Putting in the bottom didn't help at all

**Comment by Weebifying** [comment]
can you send a screenshot of your pack selection screen

**Comment by UnimosityIrux** [comment]
![Screenshot_2024-03-01-12-52-38-806_com geode launcher-edit](https://github.com/Weebifying/high-graphics-android-geode/assets/161720514/4cbc01ca-09a2-4cd4-a78e-7d7ee1d20e0f)
Here. The upper one is my own, has only 1 icon

**Comment by UnimosityIrux** [comment]
The available tab has no packs

**Comment by Weebifying** [comment]
then this is probably an issue with either how your pack is structured or what your texture quality is set to

**Comment by UnimosityIrux** [comment]
Oh, okay then :(
