### ISSUE TITLE
What do I do I don't know what happened

### ISSUE THREAD

**Issue by KipivasGD** [Weebifying/high-graphics-android-geode#9]
![Screenshot_20240301-171905](https://github.com/Weebifying/high-graphics-android-geode/assets/161895459/45d780a1-739f-40c4-b2e7-2334dcb66a7c)
![Screenshot_20240301-172700](https://github.com/Weebifying/high-graphics-android-geode/assets/161895459/cb8c315b-c43e-4d8b-adb2-e280ea7b6135)
![Screenshot_20240301-172715](https://github.com/Weebifying/high-graphics-android-geode/assets/161895459/7a7d7f58-aafa-472e-8242-fc4c595d075b)

**Comment by Weebifying** [comment]
looks like you havent fully unzipped the high-textures pack you're required to download

**Comment by KipivasGD** [comment]
> looks like you havent fully unzipped the high-textures pack you're required to download

Can you help me out a bit?

**Comment by KipivasGD** [comment]
Wq
